ALTER TABLE configs ADD COLUMN name TEXT DEFAULT '';
ALTER TABLE configs ADD COLUMN device_id TEXT DEFAULT '';
ALTER TABLE configs ADD COLUMN device_token TEXT DEFAULT '';
ALTER TABLE configs ADD COLUMN server_public_key TEXT DEFAULT '';
ALTER TABLE configs ADD COLUMN endpoint TEXT DEFAULT '162.159.192.1:2408';
ALTER TABLE configs ADD COLUMN account_type TEXT DEFAULT 'Free';
ALTER TABLE configs ADD COLUMN license_key TEXT DEFAULT '';
ALTER TABLE configs ADD COLUMN updated_at INTEGER DEFAULT 0;
